project: 
  type: website
  render: 
    - about.qmd
    - speeds_team.qmd
    - speedsR_data_package.qmd
    - Handling_Missing_Data_and_Outliers.qmd

website: 
  title: "The SPEEDS Project"
  cookie-consent:
    type: express
    style: headline
    palette: dark
    
  google-analytics: 
    tracking-id: "G-5CH3ZRNFRZ"
    anonymize-ip: true
    version: 4
    storage: cookies
    
  navbar:
    background: primary
    search: true
    left:
      - about.qmd
      - speeds_team.qmd
      - speedsR_data_package.qmd
          
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Data Management"
        contents:
            - Data_Organization.qmd
            - Data_Wrangling_Cleaning_Tidying.qmd
            - Handling_Missing_Data_and_Outliers.qmd
            - Synthetic_Data_Generation_With_synthpop.qmd
      - section: "Exploratory Data Analysis"
        contents: 
            - Data_Exploration_Techniques.qmd
      - section: "Data Visualization"
        contents:
            - Bar_Plots.qmd
            - Scatter_Plots.qmd
      - section: "Data Analysis"
        contents:
            - DimRed_intro.qmd
            - regression_1_LM.qmd
            - regression_2_Poisson.qmd
            - regression_3_Logistic.qmd
            - regression_4_LMM.qmd

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css