project: 
  type: website
  
website: 
  title: "The SPEEDS Project"
  navbar:
    background: primary
    search: true
    left:
      - about.qmd
      - speedsR_data_package.qmd
          
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Data Management"
        contents:
            - Data_Organization.qmd
            - Data_Wrangling_Cleaning_Tidying.qmd
            - Handling_Missing_Data_and_Outliers.qmd
            - Synthetic_Data_Generation_With_synthpop.qmd
      - section: "Data Visualization"
        contents:
            - Bar_Plots.qmd
            - Scatter_Plots.qmd
  
format:
  html:
    theme: zephyr
    css: styles.css